### ISSUE TITLE
Mark run ids archived to Glacier as processed 

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-python-analytics-sdk#23]
One problem here is that it doesn't seems possible to check if some prefix like `enriched-archive/run=2017-04-27-14-39-42/` was archived to glacier by simply listing `enriched-archive` and checking metadata. It's possible to archive *object*, not *prefix*.

Therefore, we most likely need to:
1. List prefixes in enriched archive
2. For each of prefix get `part-00001` key
3. Check if this key has storage class `GLACIER`
4. If it does - mark as processed, if doesn't - unprocessed, if key doesn't exist - unprocessed (?)

Approach seems a bit fragile because for some keys in prefix can probably be archived and some can be not. Not sure how likely.

Another approach would be to get lifecycle policy for bucket. And based on prefix, current date, and date in run id decide if this prefix is archived. This approach is fragile because it's not possible restore and reprocess run id.

@alexanderdean few more questions:
1. Should we just not return archived run ids from `list_run_ids` or add them to DynamoDB as well?
2. What release version it should be? 0.2.2 or 0.3.0?

**Comment by alexanderdean** [comment]
Hey @chuwy - I think this sounds good, a couple of thoughts:

> For each of prefix get part-00001 key

I would just get the first object returned at that prefix and check it. I think looking for a specific object name will just complicate things.

> Another approach would be to get lifecycle policy for bucket. And based on prefix, current date, and date in run id decide if this prefix is archived. This approach is fragile because it's not possible restore and reprocess run id.

Yep too fragile.

> Should we just not return archived run ids from list_run_ids or add them to DynamoDB as well?

I think let's just ignore rather than add to manifest. Adding to the manifest implies that this run was actually processed, whereas really we are saying "this run probably wasn't processed but it's too difficult for us to dig out".

> What release version it should be? 0.2.2 or 0.3.0?

0.2.2 is fine given that we can't safely process data that's in Glacier, so this is essentially a bug fix for that.
